name: jenkins_service
services:
  docker_dind:
    image: docker:dind
    container_name: jenkins_docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2376:2376"
    restart:
      always
    privileged: true
    networks:
      dev:
        aliases:
          - docker
  jenkins:
    build: .
    image: jenkins_build:v1
    container_name:  jenkins-blueocean
    restart: on-failure
    networks:
      - dev
    group_add:
      - 999
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JENKINS_OPTS="--prefix=/jenkinscicd"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  dev:
    driver: bridge
volumes:
  jenkins-docker-certs:
  jenkins-data: