name: jenkins_service
services:
  jenkins:
    build: .
    image: jenkins_build:v1
    container_name:  jenkins-blueocean
    restart: on-failure
    networks:
      - dev
    group_add:
      - 999
    environment:
      - DOCKER_TLS_VERIFY=0
      - JENKINS_OPTS="--prefix=/jenkinscicd"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  dev:
    driver: bridge
volumes:
  jenkins-docker-certs:
  jenkins-data: